### ISSUE TITLE
Macro results vary over multiple executions

### ISSUE THREAD

**Issue by haesleinhuepf** [imagej/ImageJ#174] opened 2021-11-11 07:00 UTC
Repeatedly calling the same macro code from pyimagej leads to different results.

See detailed description: https://forum.image.sc/t/macro-results-vary-when-calling-it-via-pyimagej/57744

**Comment by ctrueden** [comment] 2022-09-07 15:56
@rasband I transferred this issue here from PyImageJ. Based on [your forum post](https://forum.image.sc/t/macro-results-vary-when-calling-it-via-pyimagej/57744/8?u=ctrueden) I infer this might actually be working as intended, in which case this issue could be closed as not planned.

**Comment by rasband** [comment] 2022-09-07 17:12
The particle analyzer is working as expected. The Count Masks are filled with a grayscale value corresponding to the particle number. To insure the particle numbers start at 1, use the “Clear results” option, as in this example:

```
  run("Blobs (25K)");
  setAutoThreshold("Otsu");
  setOption("BlackBackground", true);
  run("Analyze Particles...", "clear show=[Count Masks]");
  getStatistics(area, mean, min, max, std, histogram);
  print(max);
```

**Closed by rasband** 2022-09-07 17:12 UTC
