### ISSUE TITLE
Console windows doesn't show stdout any more

### ISSUE THREAD

**Issue by haesleinhuepf** [imagej/imagej#183] opened 2017-12-27 19:07 UTC
Hey guys,

is it possible that with Fiji (ImageJ 2.0.0-rc-62/1.51s; Java 1.8.0_66 [64-bit], Windows 10), the console window changed? (it has tabs now)
Furthermore, it doesn't show _stdout_ anymore. Was this an intentional change? Is there an option somewhere to get the old behaviour back?

Thanks,
Robert

**Comment by ctrueden** [comment] 2017-12-28 14:12
> is it possible that with Fiji (ImageJ 2.0.0-rc-62/1.51s; Java 1.8.0_66 [64-bit], Windows 10), the console window changed?

Yes, this was the result of much effort by @maarzt on behalf of @fjug. If you do not like it, feel free to have a conversation with them (in person or here online) about what would be better.

> Furthermore, it doesn't show _stdout_ anymore.

I cannot reproduce this problem with 2.0.0-rc-62/1.51s.

All of the following snippets in the search bar produce output to the console as expected:
```
!println("hi stdout")
!System.err.println("hi stderr")
!stderrLog.info("Banging your head against a wall burns 150 calories per hour")
!stderrLog.warn("Death awaits you all, with nasty big pointy teeth")
!stderrLog.error("The operation completed successfully")
```
(It is unfortunate that the `LogService` instance gets named `stderrLog` due to the naming heuristic; that will be fixed in a future version.)

**Closed** 2017-12-28 14:22 UTC
