### ISSUE TITLE
Fiji requires ImageJ to be built with java 1.6, not 1.8

### ISSUE THREAD

**Issue by aschain** [imagej/ImageJ#149] opened 2022-01-27 21:20 UTC
I had to change this line in the build.xml
`<javac srcdir="./ij" destdir="build" optimize="on" source="1.8" target="1.8" debug="on" includeantruntime="false" encoding="utf-8">`

to 
`<javac srcdir="./ij" destdir="build" optimize="on" source="1.6" target="1.6" debug="on" includeantruntime="false" encoding="utf-8">`

in order for the ij.jar to work with Fiji.  FYI.

**Comment by aschain** [comment] 2022-02-01 17:43
Sure, I think it is ij1-patcher in Fiji that fails.

On a mac with java version:

```
% java -version
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
```
but I also have java 9 and java 13 installed.

If I git clone github.com/imagej/imagej.git and install a fresh Fiji.app, then run "ant" from the imagej folder, then copy the ij.jar to Fiji.app/jars/ij-1.53p.jar, it does not run.
The relevant parts of the debug log is below:
```
[DEBUG] Creating service: net.imagej.legacy.LegacyService
java.lang.IllegalArgumentException: Cannot modify method: public void run(java.lang.String arg)
	at net.imagej.patcher.CodeHacker.insertAtTopOfMethod(CodeHacker.java:166)
	at net.imagej.patcher.LegacyInjector.inject(LegacyInjector.java:288)
	at net.imagej.patcher.LegacyInjector.injectHooks(LegacyInjector.java:107)
	at net.imagej.patcher.LegacyEnvironment.initialize(LegacyEnvironment.java:100)
	at net.imagej.patcher.LegacyEnvironment.applyPatches(LegacyEnvironment.java:494)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:395)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:374)
	at net.imagej.legacy.LegacyService.<clinit>(LegacyService.java:141)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:300)
	at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:267)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:229)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:192)
	at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:164)
	at org.scijava.Context.<init>(Context.java:278)
	at org.scijava.Context.<init>(Context.java:234)
	at org.scijava.Context.<init>(Context.java:174)
	at org.scijava.Context.<init>(Context.java:160)
	at net.imagej.ImageJ.<init>(ImageJ.java:77)
	at net.imagej.Main.main(Main.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:291)
	at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:198)
	at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:89)
Caused by: java.lang.IllegalArgumentException: No such class: MacAdapter
	at net.imagej.patcher.CodeHacker.getClass(CodeHacker.java:878)
	at net.imagej.patcher.CodeHacker.getMethod(CodeHacker.java:904)
	at net.imagej.patcher.CodeHacker.getBehavior(CodeHacker.java:894)
	at net.imagej.patcher.CodeHacker.insertAtTopOfMethod(CodeHacker.java:157)
	... 30 more
Caused by: javassist.NotFoundException: MacAdapter
	at javassist.ClassPool.get(ClassPool.java:430)
	at net.imagej.patcher.CodeHacker.getClass(CodeHacker.java:873)
	... 33 more
java.lang.IllegalArgumentException: Method void createMacro() in ij.plugin.frame.Recorder does not return on null
	at net.imagej.patcher.CodeHacker.dontReturnOnNull(CodeHacker.java:497)
	at net.imagej.patcher.LegacyExtensions.addEditorExtensionPoints(LegacyExtensions.java:320)
	at net.imagej.patcher.LegacyExtensions.injectHooks(LegacyExtensions.java:287)
	at net.imagej.patcher.LegacyInjector.inject(LegacyInjector.java:306)
	at net.imagej.patcher.LegacyInjector.injectHooks(LegacyInjector.java:107)
	at net.imagej.patcher.LegacyEnvironment.initialize(LegacyEnvironment.java:100)
	at net.imagej.patcher.LegacyEnvironment.applyPatches(LegacyEnvironment.java:494)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:395)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:374)
	at net.imagej.legacy.LegacyService.<clinit>(LegacyService.java:141)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:300)
	at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:267)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:229)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:192)
	at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:164)
	at org.scijava.Context.<init>(Context.java:278)
	at org.scijava.Context.<init>(Context.java:234)
	at org.scijava.Context.<init>(Context.java:174)
	at org.scijava.Context.<init>(Context.java:160)
	at net.imagej.ImageJ.<init>(ImageJ.java:77)
	at net.imagej.Main.main(Main.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:291)
	at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:198)
	at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:89)
java.lang.IllegalArgumentException: Cannot handle replace call to runPlugIn in ij.plugin.frame.Recorder's void createMacro()
	at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:723)
	at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:648)
	at net.imagej.patcher.LegacyExtensions.addEditorExtensionPoints(LegacyExtensions.java:321)
	at net.imagej.patcher.LegacyExtensions.injectHooks(LegacyExtensions.java:287)
	at net.imagej.patcher.LegacyInjector.inject(LegacyInjector.java:306)
	at net.imagej.patcher.LegacyInjector.injectHooks(LegacyInjector.java:107)
	at net.imagej.patcher.LegacyEnvironment.initialize(LegacyEnvironment.java:100)
	at net.imagej.patcher.LegacyEnvironment.applyPatches(LegacyEnvironment.java:494)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:395)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:374)
	at net.imagej.legacy.LegacyService.<clinit>(LegacyService.java:141)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:300)
	at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:267)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:229)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:192)
	at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:164)
	at org.scijava.Context.<init>(Context.java:278)
	at org.scijava.Context.<init>(Context.java:234)
	at org.scijava.Context.<init>(Context.java:174)
	at org.scijava.Context.<init>(Context.java:160)
	at net.imagej.ImageJ.<init>(ImageJ.java:77)
	at net.imagej.Main.main(Main.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:291)
	at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:198)
	at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:89)
Caused by: javassist.CannotCompileException: No code replaced!
	at net.imagej.patcher.CodeHacker$EagerExprEditor.instrument(CodeHacker.java:1290)
	at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:720)
	... 33 more
java.lang.IllegalArgumentException: Cannot modify method: public void run(java.lang.String arg)
	at net.imagej.patcher.CodeHacker.insertAtTopOfMethod(CodeHacker.java:166)
	at net.imagej.patcher.LegacyExtensions.handleMacAdapter(LegacyExtensions.java:556)
	at net.imagej.patcher.LegacyExtensions.injectHooks(LegacyExtensions.java:292)
	at net.imagej.patcher.LegacyInjector.inject(LegacyInjector.java:306)
	at net.imagej.patcher.LegacyInjector.injectHooks(LegacyInjector.java:107)
	at net.imagej.patcher.LegacyEnvironment.initialize(LegacyEnvironment.java:100)
	at net.imagej.patcher.LegacyEnvironment.applyPatches(LegacyEnvironment.java:494)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:395)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:374)
	at net.imagej.legacy.LegacyService.<clinit>(LegacyService.java:141)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:300)
	at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:267)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:229)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:192)
	at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:164)
	at org.scijava.Context.<init>(Context.java:278)
	at org.scijava.Context.<init>(Context.java:234)
	at org.scijava.Context.<init>(Context.java:174)
	at org.scijava.Context.<init>(Context.java:160)
	at net.imagej.ImageJ.<init>(ImageJ.java:77)
	at net.imagej.Main.main(Main.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:291)
	at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:198)
	at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:89)
Caused by: java.lang.IllegalArgumentException: No such class: MacAdapter
	at net.imagej.patcher.CodeHacker.getClass(CodeHacker.java:878)
	at net.imagej.patcher.CodeHacker.getMethod(CodeHacker.java:904)
	at net.imagej.patcher.CodeHacker.getBehavior(CodeHacker.java:894)
	at net.imagej.patcher.CodeHacker.insertAtTopOfMethod(CodeHacker.java:157)
	... 32 more
Caused by: javassist.NotFoundException: MacAdapter
	at javassist.ClassPool.get(ClassPool.java:430)
	at net.imagej.patcher.CodeHacker.getClass(CodeHacker.java:873)
	... 35 more
java.lang.IllegalArgumentException: Cannot handle replace call to openImage in ij.plugin.FolderOpener's public void run(java.lang.String arg)
	at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:723)
	at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:648)
	at net.imagej.patcher.LegacyExtensions.installOpenInterceptor(LegacyExtensions.java:764)
	at net.imagej.patcher.LegacyExtensions.injectHooks(LegacyExtensions.java:294)
	at net.imagej.patcher.LegacyInjector.inject(LegacyInjector.java:306)
	at net.imagej.patcher.LegacyInjector.injectHooks(LegacyInjector.java:107)
	at net.imagej.patcher.LegacyEnvironment.initialize(LegacyEnvironment.java:100)
	at net.imagej.patcher.LegacyEnvironment.applyPatches(LegacyEnvironment.java:494)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:395)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:374)
	at net.imagej.legacy.LegacyService.<clinit>(LegacyService.java:141)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:300)
	at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:267)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:229)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:192)
	at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:164)
	at org.scijava.Context.<init>(Context.java:278)
	at org.scijava.Context.<init>(Context.java:234)
	at org.scijava.Context.<init>(Context.java:174)
	at org.scijava.Context.<init>(Context.java:160)
	at net.imagej.ImageJ.<init>(ImageJ.java:77)
	at net.imagej.Main.main(Main.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:291)
	at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:198)
	at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:89)
Caused by: javassist.CannotCompileException: No code replaced!
	at net.imagej.patcher.CodeHacker$EagerExprEditor.instrument(CodeHacker.java:1290)
	at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:720)
	... 33 more
[ERROR] Invalid service: net.imagej.legacy.LegacyService
java.lang.VerifyError: Expecting a stack map frame
Exception Details:
  Location:
    ij/IJ.getClassLoader()Ljava/lang/ClassLoader; @176: nop
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: b20b ae01 a600 24b8 005b b60b b1b3 0bae
    0x0000010: b20b ae04 b80b b54b 2a01 a500 0eb8 005b
    0x0000020: 2ab6 0b6e 2ab3 0bae b20b aeb0 0000 00a7
    0x0000030: fffd 0000 0000 00a7 fffb 0000 0000 0000
    0x0000040: 0000 0000 0000 0000 0000 0000 a7ff ee00
    0x0000050: 0000 0000 0000 a7ff f9a7 0000 0000 a7ff
    0x0000060: fe00 0000 00a7 fffc 0000 0000 0000 00a7
    0x0000070: fff9 0000 0000 0000 0000 0000 0000 0000
    0x0000080: 0000 0000 a7ff ee00 0000 0000 0000 0000
    0x0000090: 0000 0000 0000 0000 0000 0000 0000 0000
    0x00000a0: 0000 0000 0000 0000 0000 0000 00a7 ffda
    0x00000b0: 00bf 00a7 ffff 0000 0000 a7ff fc00 0000
    0x00000c0: a7ff fd00 0000 0000 0000 0000 0000 00a7
    0x00000d0: fff4 0000 0000 0000 0000 a7ff f800 a7ff
    0x00000e0: ff                                     
  Stackmap Table:
    same_frame(@40)
    same_frame(@44)
    same_frame(@50)
    same_frame(@58)
    same_frame(@79)
    same_frame(@89)
    same_frame(@92)
    same_frame(@97)
    same_frame(@104)
    same_frame(@114)
    same_frame(@135)
    same_frame(@178)
    same_frame(@182)
    same_frame(@189)
    same_frame(@195)
    same_frame(@210)
    same_frame(@221)

	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getField0(Class.java:2975)
	at java.lang.Class.getField(Class.java:1701)
	at net.imagej.patcher.LegacyEnvironment.initialize(LegacyEnvironment.java:104)
	at net.imagej.patcher.LegacyEnvironment.applyPatches(LegacyEnvironment.java:494)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:395)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:374)
	at net.imagej.legacy.LegacyService.<clinit>(LegacyService.java:141)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:300)
	at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:267)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:229)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:192)
	at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:164)
	at org.scijava.Context.<init>(Context.java:278)
	at org.scijava.Context.<init>(Context.java:234)
	at org.scijava.Context.<init>(Context.java:174)
	at org.scijava.Context.<init>(Context.java:160)
	at net.imagej.ImageJ.<init>(ImageJ.java:77)
	at net.imagej.Main.main(Main.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:291)
	at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:198)
	at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:89)
[ERROR] No match: net.imagej.legacy.LegacyService
```
and 
```
[DEBUG] Received command line arguments:
[ERROR] Exception during event handling:
	[Event] org.scijava.service.event.ServicesLoadedEvent
	context = org.scijava.Context@b5b5125
	consumed = false
	[Subscriber] sc.fiji.compat.DefaultFijiService [priority = 0.0]
	[Method] protected void sc.fiji.compat.DefaultFijiService.onEvent(org.scijava.service.event.ServicesLoadedEvent)
java.lang.VerifyError: Expecting a stack map frame
Exception Details:
  Location:
    ij/IJ.getClassLoader()Ljava/lang/ClassLoader; @176: nop
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: b20b ae01 a600 24b8 005b b60b b1b3 0bae
    0x0000010: b20b ae04 b80b b54b 2a01 a500 0eb8 005b
    0x0000020: 2ab6 0b6e 2ab3 0bae b20b aeb0 0000 00a7
    0x0000030: fffd 0000 0000 00a7 fffb 0000 0000 0000
    0x0000040: 0000 0000 0000 0000 0000 0000 a7ff ee00
    0x0000050: 0000 0000 0000 a7ff f9a7 0000 0000 a7ff
    0x0000060: fe00 0000 00a7 fffc 0000 0000 0000 00a7
    0x0000070: fff9 0000 0000 0000 0000 0000 0000 0000
    0x0000080: 0000 0000 a7ff ee00 0000 0000 0000 0000
    0x0000090: 0000 0000 0000 0000 0000 0000 0000 0000
    0x00000a0: 0000 0000 0000 0000 0000 0000 00a7 ffda
    0x00000b0: 00bf 00a7 ffff 0000 0000 a7ff fc00 0000
    0x00000c0: a7ff fd00 0000 0000 0000 0000 0000 00a7
    0x00000d0: fff4 0000 0000 0000 0000 a7ff f800 a7ff
    0x00000e0: ff                                     
  Stackmap Table:
    same_frame(@40)
    same_frame(@44)
    same_frame(@50)
    same_frame(@58)
    same_frame(@79)
    same_frame(@89)
    same_frame(@92)
    same_frame(@97)
    same_frame(@104)
    same_frame(@114)
    same_frame(@135)
    same_frame(@178)
    same_frame(@182)
    same_frame(@189)
    same_frame(@195)
    same_frame(@210)
    same_frame(@221)

	at sc.fiji.compat.DefaultFijiService.actuallyInitialize(DefaultFijiService.java:54)
	at sc.fiji.compat.DefaultFijiService.onEvent(DefaultFijiService.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.scijava.event.DefaultEventService$ProxySubscriber.onEvent(DefaultEventService.java:298)
	at org.scijava.event.DefaultEventService$ProxySubscriber.onEvent(DefaultEventService.java:272)
	at org.bushe.swing.event.ThreadSafeEventService.publish(ThreadSafeEventService.java:971)
	at org.scijava.event.DefaultEventBus.access$201(DefaultEventBus.java:54)
	at org.scijava.event.DefaultEventBus$2.run(DefaultEventBus.java:214)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$1(DefaultThreadService.java:211)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] java.lang.IllegalArgumentException: Required service is missing: net.imagej.legacy.LegacyService
Context: org.scijava.Context@b5b5125
ClassLoader: sun.misc.Launcher$AppClassLoader@c387f44
```
and, at the end
```
/Users/aschain/Applications/Fiji-fresh.app/plugins/View5D_-2.3.1.jar

	at org.scijava.Context.inject(Context.java:483)
	at org.scijava.Context.inject(Context.java:383)
	at org.scijava.plugin.DefaultPluginService.createInstance(DefaultPluginService.java:235)
	at org.scijava.ui.DefaultUIService.discoverUIs(DefaultUIService.java:504)
	at org.scijava.ui.DefaultUIService.getDefaultUI(DefaultUIService.java:191)
	at org.scijava.ui.DefaultUIService.showUI(DefaultUIService.java:137)
	at org.scijava.AbstractGateway.launch(AbstractGateway.java:110)
	at net.imagej.Main.main(Main.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:291)
	at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:198)
	at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:89)
[DEBUG] Discovered user interface: net.imagej.legacy.ui.LegacyUI
[DEBUG] Discovered user interface: org.scijava.ui.swing.sdi.SwingSDIUI
[DEBUG] Discovered user interface: org.scijava.ui.awt.AWTUI
[DEBUG] Discovered user interface: org.scijava.ui.swing.mdi.SwingMdiUI
[DEBUG] Discovered user interface: org.scijava.ui.headless.HeadlessUI
[DEBUG] Launching user interface: net.imagej.legacy.ui.LegacyUI
Error while executing the main() method of class 'net.imagej.Main':
java.lang.NullPointerException
	at net.imagej.legacy.ui.LegacyUI.ij1Helper(LegacyUI.java:119)
	at net.imagej.legacy.ui.LegacyUI.show(LegacyUI.java:130)
	at org.scijava.ui.DefaultUIService.showUI(DefaultUIService.java:158)
	at org.scijava.ui.DefaultUIService.showUI(DefaultUIService.java:143)
	at org.scijava.AbstractGateway.launch(AbstractGateway.java:110)
	at net.imagej.Main.main(Main.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:291)
	at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:198)
	at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:89)
```

Hope this helps.

**Comment by ctrueden** [comment] 2022-02-01 22:10
@aschain Thanks, that's really helpful!

I see that @rasband noted something similar in https://github.com/imagej/ij1-patcher/issues/50#issuecomment-754720375, where we are tracking the fact that ij1-patcher in general does not support the newest versions of ImageJ. It's on [my list](https://imagej.net/people/ctrueden#immediate-priorities) to fix (after 14 other projects... 😅). As part of that, I can dig into the `VerifyError` here as well, to better understand the differences in bytecode between target Java versions.

**Comment by ctrueden** [comment] 2022-03-27 17:30
The releases of ImageJ 1.53k through 1.53p released to Maven Central last week were built with Java 11, targeting Java 6 (except for `module-info` which must target Java 9). I am unable to reproduce the `VerifyError`s with these release builds, so I'm closing this issue. Please reopen if you find otherwise on your system.

Note that the ij1-patcher still does not fully work with 1.53g and later, but we are working on it; see imagej/ij1-patcher#50. So while you should not be seeing `VerifyError` with newer ImageJ versions now, you will still see a few stack traces, and portions of ImageJ may not work as expected due to patching failures.

**Closed by ctrueden** 2022-03-27 17:30 UTC
